## Welcome to numpy tutorial

In [4]:
import numpy as np

In [5]:
myarr = np.array([[3,6,37,7]] , np.int64)

In [6]:
myarr[0,1]

np.int64(6)

In [7]:
myarr[0,1] = 45 

In [8]:
myarr

array([[ 3, 45, 37,  7]])

In [9]:
myarr.shape

(1, 4)

In [10]:
myarr.dtype

dtype('int64')

## Array creation :conversion from other python structures

In [13]:
listarray = np.array([[1,2,3] , [5,8,5] , [0,3,1]])

In [15]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [17]:
listarray.dtype

dtype('int64')

In [18]:
listarray.shape

(3, 3)

In [19]:
listarray.size

9

In [20]:
zeros = np.zeros((2,5))

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
rng = np.arange(15)

In [24]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
lspace = np.linspace(1,5,12)

In [26]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [31]:
emp = np.empty((4,6))

In [32]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.33511290e-306, 6.23058368e-307, 8.90105597e-307],
       [6.23053614e-307, 7.56592338e-307, 1.60220528e-306,
        7.56602523e-307, 1.42417221e-306, 1.37961641e-306],
       [2.22522597e-306, 1.33511969e-306, 6.23037996e-307,
        6.23053954e-307, 9.34609790e-307, 8.45593934e-307],
       [9.34600963e-307, 1.86921143e-306, 6.23061763e-307,
        1.60220393e-306, 9.34605037e-307, 1.42417901e-306]])

In [33]:
emp_like = np.empty_like(lspace)

In [34]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [35]:
ide = np.identity(45)

In [36]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [38]:
ide.shape

(45, 45)

In [39]:
arr = np.arange(99)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [43]:
 arr = arr.ravel()

In [44]:
arr.shape

(99,)

# Numpy axis 

In [45]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [46]:
ar = np.array(x)

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar.sum(axis=0)

array([12,  8,  9])

In [49]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [50]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
ar.flat

In [52]:
ar.ndim

2

In [53]:
ar.size

9

In [54]:
ar.nbytes

72

In [55]:
one = np.array([1,3,4,634,2])

In [56]:
one.argmax()

np.int64(3)

In [57]:
one.argmin()

np.int64(0)

In [58]:
one.argsort()

array([0, 4, 1, 2, 3])

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [61]:
ar.argmin()

np.int64(8)

In [62]:
ar.argmax()

np.int64(6)

In [64]:
ar.argmax(axis=1)

array([2, 2, 0])

In [66]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [67]:
ar.reshape((9))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [68]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [69]:
ar2 =np.array ([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [70]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [71]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [72]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [73]:
ar.sum()

np.int64(29)

In [74]:
ar.min()

np.int64(0)

In [75]:
ar.max()

np.int64(7)

In [76]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [77]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [78]:
np.count_nonzero(ar)

np.int64(8)

In [82]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [83]:
import sys

In [84]:
py_ar = [0,4,55,2]

In [85]:
np_ar = np.array(py_ar)

In [86]:
sys.getsizeof(1) * len(py_ar)

112

In [88]:
np_ar.itemsize * np_ar.size

32

In [90]:
np_ar.tolist()

[0, 4, 55, 2]